apiVersion: v1
kind: Secret
metadata:
  name: {{ include "be.fullname" . }}
  labels:
    {{- include "be.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
