# ============================================
# BRIX Frontend - PROD Environment
# ============================================

replicaCount: 1

image:
  repository: jonasaugust12/brix-web
  # -- Always pin to a specific version in prod
  tag: "prod-b3c8dcd"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: brix.social
      paths:
        - path: /
          pathType: Prefix
    - host: www.brix.social
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: brix-fe-prod-tls
      hosts:
        - brix.social
        - www.brix.social

imagePullSecrets:
  - name: regcred

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80
