# ============================================
# BRIX Frontend - PROD Environment
# ============================================

replicaCount: 1

image:
  repository: jonasaugust12/brix-web
  # -- Always pin to a specific version in prod
  tag: "prod-b3c8dcd"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # -- TODO: Uncomment below when SSL is configured
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: brix.social
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # -- TODO: Uncomment below when SSL is configured
  # tls:
  #   - secretName: brix-fe-tls
  #     hosts:
  #       - brix.social

imagePullSecrets:
  - name: regcred

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80
