# ============================================
# Redis - PROD Environment (Bitnami Chart)
# ============================================

image:
  repository: bitnami/redis
  tag: 7.4

auth:
  enabled: false

# -- Enable replication for prod
architecture: replication

master:
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "local-path"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "local-path"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

metrics:
  enabled: true
  image:
    repository: bitnami/redis-exporter
    tag: latest
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
