---
- name: Setup K3s and ArgoCD on AWS EC2
  hosts: all
  become: yes
  vars:
    k3s_version: "v1.30.2+k3s1"

  tasks:
    - name: Wait for server to finish booting
      wait_for_connection:
        timeout: 300

    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -s - server --write-kubeconfig-mode 644
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s node to be ready
      shell: k3s kubectl get nodes | grep " Ready"
      register: k3s_ready
      until: k3s_ready.rc == 0
      retries: 10
      delay: 5

    - name: Ensure app namespaces exist
      shell: |
        k3s kubectl create namespace brix-dev --dry-run=client -o yaml | k3s kubectl apply -f -
        k3s kubectl create namespace brix-prod --dry-run=client -o yaml | k3s kubectl apply -f -

    - name: Create Docker Registry Secret (regcred)
      shell: |
        k3s kubectl create secret docker-registry regcred \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username="{{ lookup('env', 'DOCKERHUB_USERNAME') }}" \
          --docker-password="{{ lookup('env', 'DOCKERHUB_PASSWORD') }}" \
          --docker-email="{{ lookup('env', 'DOCKERHUB_EMAIL') }}" \
          -n {{ item }} --dry-run=client -o yaml | k3s kubectl apply -f -
      loop:
        - brix-dev
        - brix-prod
      when: lookup('env', 'DOCKERHUB_USERNAME') != ""

    - name: Add GitHub PAT Secret for ArgoCD (Private Repository Access)
      shell: |
        cat <<EOF | k3s kubectl apply -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: github-repo-creds
          namespace: argocd
          labels:
            argocd.argoproj.io/secret-type: repository
        stringData:
          url: "https://github.com/BRIX-ORG/BRIX-Configuration.git"
          password: "{{ lookup('env', 'GITHUB_PAT') }}"
          username: "git"
        EOF
      when: lookup('env', 'GITHUB_PAT') != ""

    - name: Copy root-app.yaml to server
      copy:
        src: ../root-app.yaml
        dest: /tmp/root-app.yaml

    - name: Copy ArgoCD Ingress to server
      copy:
        src: ./argocd-ingress.yaml
        dest: /tmp/argocd-ingress.yaml

    - name: Deploy the ArgoCD Root Application
      shell: k3s kubectl apply -f /tmp/root-app.yaml

    - name: Deploy the ArgoCD Ingress
      shell: k3s kubectl apply -f /tmp/argocd-ingress.yaml

    - name: Get ArgoCD Admin Password
      shell: k3s kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      register: argocd_password

    - name: Display ArgoCD Credentials
      debug:
        msg: 
          - "ArgoCD URL: http://argocd.brix.social"
          - "Username: admin"
          - "Password: {{ argocd_password.stdout }}"
