# ============================================
# Redis - DEV Environment (Bitnami Chart)
# ============================================
# Chart: https://github.com/bitnami/charts/tree/main/bitnami/redis

image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 7.4.2-debian-12-r4

# -- Disable auth for dev simplicity
auth:
  enabled: false

# -- Disable replication for dev
architecture: standalone

master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "local-path"

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

metrics:
  enabled: false
  image:
    repository: bitnamilegacy/redis-exporter
    tag: latest
